name: DynamicEarthNet
global_batch_size: 2
num_channels: 4
num_classes: 6
ignore_index: 6
class_names: ["impervi", "agricult", "forest", "wetlands", "soil", "water"]


train_dataset:
  _partial_: true
  _target_: data.data.DynamicEarthNet
  path: ${data_dir}/DynamicEarthNet/
  split: train
  train_length: 12 # Using 12 months for training in no domain shift and spatial domain shift, 6 months for temporal domain shift
  date_aug_range: 2
  domain_shift_type: ${domain_shift_type}
  img_size: 64

val_dataset_out:
  _partial_: true
  _target_: data.data.DynamicEarthNet
  path: ${data_dir}/DynamicEarthNet/
  split: val
  domain_shift_type: spatial
  img_size: 64

val_dataset_temporal:
  _partial_: true
  _target_: data.data.DynamicEarthNet 
  path: ${data_dir}/DynamicEarthNet/
  split: val
  domain_shift_type: temporal
  img_size: 64

val_dataset_in:
  _partial_: true
  _target_: data.data.DynamicEarthNet
  path: ${data_dir}/DynamicEarthNet/
  split: val
  domain_shift_type: none
  img_size: 64

test_dataset_out:
  _partial_: true
  _target_: data.data.DynamicEarthNet
  path: ${data_dir}/DynamicEarthNet/
  split: test
  domain_shift_type: spatial
  img_size: 64

test_dataset_temporal:
  _partial_: true
  _target_: data.data.DynamicEarthNet
  path: ${data_dir}/DynamicEarthNet/
  split: test
  domain_shift_type: temporal
  img_size: 64

test_dataset_in:
  _partial_: true
  _target_: data.data.DynamicEarthNet
  path: ${data_dir}/DynamicEarthNet/
  split: test
  domain_shift_type: none
  img_size: 64
